replicaCount: 1

image:
  repository: asia-southeast1-docker.pkg.dev/ctse-micro/mri-service/mri-service
  tag: 2022dfcd5b3db6e2a1d2016f1843d1c345cdf188
  pullPolicy: Always

service:
  type: NodePort
  port: 8000

serviceAccount:
  create: false

ingress:
  enabled: false

autoscaling:
  enabled: false
