ingress:
  enabled: false
  className: nginx 
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - hosts:
        - "cognicare.dementiaguard.live"
      # secretName: cognicare-cert
  hosts:
    - host: "cognicare.dementiaguard.live"
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cognicare-admin-frontend-service
              port:
                number: 6757
        - path: /gateway/
          pathType: Prefix
          backend:
            service:
              name: cognicare-gateway-service
              port:
                number: 8349

cognicareIngress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - hosts:
        - cognicare.dementiaguard.live
      secretName: cognicare-cert
  hosts:
    - host: cognicare.dementiaguard.live
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cognicare-admin-frontend-service
              port:
                number: 6757
        - path: /gateway/
          pathType: Prefix
          backend:
            service:
              name: cognicare-gateway-service
              port:
                number: 8349

# Grafana namespace configuration
grafanaIngress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - hosts:
        - grafana.cognicare.dementiaguard.live
      secretName: grafana-cert
  hosts:
    - host: grafana.cognicare.dementiaguard.live
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: grafana
              port:
                number: 80

# ArgoCD namespace configuration
argocdIngress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"  # Important for ArgoCD
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    - hosts:
        - argocd.cognicare.dementiaguard.live
      secretName: argocd-cert
  hosts:
    - host: argocd.cognicare.dementiaguard.live
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: argocd-server
              port:
                number: 443

managedCertificates:
  enabled: true
  certs:
    - name: cognicare-cert
      namespace: cognicare
      domain: cognicare.dementiaguard.live
    - name: grafana-cert
      namespace: monitoring
      domain: grafana.cognicare.dementiaguard.live
    - name: argocd-cert
      namespace: argocd
      domain: argocd.cognicare.dementiaguard.live