replicaCount: 1

image:
  repository: asia-southeast1-docker.pkg.dev/ctse-micro/treatment-planning-service/treatment-planning-service
  tag: bb494f1a440883df42095329662d71edbdd3e044
  pullPolicy: Always

service:
  type: NodePort
  port: 8000

serviceAccount:
  create: false

ingress:
  enabled: false

autoscaling:
  enabled: false
