{{- if .Values.managedCertificates.enabled }}
{{- range .Values.managedCertificates.certs }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  domains:
    - {{ .domain }}
---
{{- end }}
{{- end }}